### ISSUE TITLE
undefined method 'bytesize' in README.md example

### ISSUE THREAD

**Issue by chrchr** [jwagener-soundcloud/httmultiparty#22]
Running this code:

```
require 'httmultiparty'
class SomeClient
  include HTTMultiParty
  base_uri 'http://localhost:3000'
end

response = SomeClient.post('/', :query => {
  :foo      => 'bar',
  :somefile => File.new('README.md')
})
```

Gives this failure:

```
/Users/rc/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1932:in `send_request_with_body': undefined method `bytesize' for #<Array:0x007fae833bc7c8> (NoMethodError)
    from /Users/rc/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1919:in `exec'
    from /Users/rc/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1317:in `block in transport_request'
    from /Users/rc/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
    from /Users/rc/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1316:in `transport_request'
    from /Users/rc/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1293:in `request'
    from /Users/rc/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1286:in `block in request'
    from /Users/rc/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:745:in `start'
    from /Users/rc/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1284:in `request'
    from /Users/rc/.rvm/gems/ruby-1.9.3-p392/gems/httparty-0.11.0/lib/httparty/request.rb:92:in `perform'
    from /Users/rc/.rvm/gems/ruby-1.9.3-p392/gems/httparty-0.11.0/lib/httparty/request.rb:182:in `handle_response'
    from /Users/rc/.rvm/gems/ruby-1.9.3-p392/gems/httparty-0.11.0/lib/httparty/request.rb:106:in `perform'
    from /Users/rc/.rvm/gems/ruby-1.9.3-p392/gems/httparty-0.11.0/lib/httparty.rb:461:in `perform_request'
    from /Users/rc/.rvm/gems/ruby-1.9.3-p392/gems/httmultiparty-0.3.10/lib/httmultiparty.rb:81:in `post'
    from ./tst.rb:7:in `<main>'
```

**Comment by zbeat** [comment]
👍  I'm getting this same error, when our app tries to make a multipart POST to a resource that redirects.  In this case, the redirect was a simple HTTP to HTTPS, so we could manually workaround this by correcting the `path`.
